<a href="https://colab.research.google.com/github/scrodenbug/Simple-ML-algorithms/blob/main/FDS_Assignment_86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


###IMPLEMENTATION OF PYTHON CODE FOR ML ALGORITHMS






**SVM Classification**

**IRIS dataset**

The dataset contains three species of flowers of Iris species and their sepal, petal and other measurements. We use SVM to classify these flowers into the three species present.


In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
!pwd
iris=pd.read_csv("/content/drive/MyDrive/IRIS (1).csv")
iris.head()

/content


sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Train test split

In [ ]:
from sklearn.model_selection import train_test_split
x=iris.iloc[:,:-1]#extracting the first 4 feature columns
y=iris.iloc[:,4]#extracting the last column which has the label
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.20)

SVM

In [ ]:
from sklearn.svm import SVC
model=SVC()

In [ ]:
model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
prediction=model.predict(x_test)

In [ ]:
print(prediction)

['Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor']


METRICS

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print("Confusion matrix\n",confusion_matrix(y_test,prediction))
print("REPORT\n",classification_report(y_test,prediction))


Confusion matrix
 [[11  0  0]
 [ 0 11  1]
 [ 0  0  7]]
REPORT
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.88      1.00      0.93         7

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



**K-Means Clustering**

**Penguin data**

This dataset contains the size and measurements of the various body parts of penguins of various species. We use KMeans clustering to categorize the penguins into various species and compare this value with the species label in the dataset.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
penguin=pd.read_csv("/content/drive/MyDrive/penguins_size.csv")
penguin.head()


species     island  culmen_length_mm  ...  flipper_length_mm  body_mass_g     sex
0  Adelie  Torgersen              39.1  ...              181.0       3750.0    MALE
1  Adelie  Torgersen              39.5  ...              186.0       3800.0  FEMALE
2  Adelie  Torgersen              40.3  ...              195.0       3250.0  FEMALE
3  Adelie  Torgersen               NaN  ...                NaN          NaN     NaN
4  Adelie  Torgersen              36.7  ...              193.0       3450.0  FEMALE

[5 rows x 7 columns]

In [ ]:
penguin['sex'].fillna(penguin['sex'].mode()[0],inplace=True)
col_to_be_imputed = ['culmen_length_mm', 'culmen_depth_mm','flipper_length_mm', 'body_mass_g']
for item in col_to_be_imputed:
    penguin[item].fillna(penguin[item].mean(),inplace=True)

In [ ]:
penguin.loc[336,'sex'] = 'FEMALE'#this particular entry has a '.' instead of a valid value

In [ ]:
from sklearn.preprocessing import StandardScaler
penguin['species']=penguin['species'].map({'Adelie':0,'Chinstrap':1,'Gentoo':2,})
#here we encode the species values to integers for applying KMeans

dummies = pd.get_dummies(penguin[['island','sex']],drop_first=True)
d_scaled = penguin.drop(['island','sex'],axis=1)
#The data is to be normalised and hence the text type columns are dropped


target = d_scaled.species
d_feat= d_scaled.drop('species',axis=1)
scaler = StandardScaler()
#Standard Scaler applied to preprocess and normalize the data


scaler.fit(d_feat)
df_scaled = scaler.transform(d_feat)
df_scaled = pd.DataFrame(d_scaled,columns=d_feat.columns[:4])

df_preprocessed = pd.concat([d_scaled,dummies,target],axis=1)#add back the removed text based columns


df_preprocessed.head()

species  culmen_length_mm  ...  sex_MALE  species
0        0          39.10000  ...         1        0
1        0          39.50000  ...         0        0
2        0          40.30000  ...         0        0
3        0          43.92193  ...         1        0
4        0          36.70000  ...         0        0

[5 rows x 9 columns]

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.cluster import KMeans
kmeans = KMeans(3,init='k-means++')
kmeans.fit(df_preprocessed.drop('species',axis=1))
print(confusion_matrix(penguin.species,kmeans.labels_))

[[112   0  40]
 [ 52   0  16]
 [  1  68  55]]


Note: Here we are fixing value of k to be 3 based on the species list in the data. This can be effectively chosen using Elbow methodlogy by iterating through various values of K and choosing the best suited.

In [ ]:
print(classification_report(penguin.species,kmeans.labels_))

              precision    recall  f1-score   support

           0       0.68      0.74      0.71       152
           1       0.00      0.00      0.00        68
           2       0.50      0.44      0.47       124

    accuracy                           0.49       344
   macro avg       0.39      0.39      0.39       344
weighted avg       0.48      0.49      0.48       344

